describe('register spec', () => {
    it('success register', () => {
      cy.visit('https://primecodex.com/')
      cy.get('[href="/register/"] > .w-32').click()
      cy.get('#form-id-fullName').type('Huni Huraira')
      cy.get('#1').type('hunihuraira@gmail.com')
      cy.get('.arrow').click()
      cy.get('.search-box').type("indonesia")
      cy.get('.country').contains('Indonesia').click()
      cy.get('.m-0 > .form-control').type("082287453678")
      cy.get('#4 ').type("Testing@2023")
      cy.get('#5 ').type("Testing@2023")
      cy.get('.w-48').click()
      cy.get('#form-id-country').type("Indonesia")
      cy.get('#1').type("Indonesia")
      cy.get('#2 ').type("Jawa Timur")
      cy.get('#4 ').type("Jl Raden Patah")
      cy.get('.w-6').click()
      cy.get('.w-48').click()
      cy.get(':nth-child(3) > form > .justify-start > .w-6').click()
      cy.get('.border-1 > .w-6').click()
      cy.contains('Open Account').click();
    })
  
    it('empty fullname', () => {
      cy.visit('https://primecodex.com/')
      cy.get('[href="/register/"] > .w-32').click()
      cy.get('#1').type('hunihuraira@gmail.com')
      cy.get('.arrow').click()
      cy.get('.search-box').type("indonesia")
      cy.get('.country').contains('Indonesia').click()
      cy.get('.m-0 > .form-control').type("082287453678")
      cy.get('#4 ').type("Testing@2023")
      cy.get('#5 ').type("Testing@2023")
      cy.get('.w-48').click()
      cy.get('#swal2-title').should('contain.text','OOPS!')
    })
  
    it('empty phone number', () => {
      cy.visit('https://primecodex.com/')
      cy.get('[href="/register/"] > .w-32').click()
      cy.get('#form-id-fullName').type('Mona Lisa')
      cy.get('#1').type('hunihuraira@gmail.com')
      cy.get('.arrow').click()
      cy.get('.search-box').type("indonesia")
      cy.get('.country').contains('Indonesia').click()
      cy.get('#4 ').type("Testing@2023")
      cy.get('#5 ').type("Testing@2023")
      cy.get('.w-48').click()
      cy.get('#form-id-country').type("Indonesia")
      cy.get('#1').type("Indonesia")
      cy.get('#2 ').type("Jawa Timur")
      cy.get('#4 ').type("Jl Raden Patah")
      cy.get('.w-6').click()
      cy.get('.w-48').click()
      cy.get(':nth-child(3) > form > .justify-start > .w-6').click()
      cy.get('.border-1 > .w-6').click()
      cy.contains('Open Account').click();
    })
  
    it('empty email', () => {
      cy.visit('https://primecodex.com/')
      cy.get('[href="/register/"] > .w-32').click()
      cy.get('#form-id-fullName').type('Mona Lisa')
      cy.get('.arrow').click()
      cy.get('.search-box').type("indonesia")
      cy.get('.country').contains('Indonesia').click()
      cy.get('.m-0 > .form-control').type("082287453678")
      cy.get('#4 ').type("Testing@2023")
      cy.get('#5 ').type("Testing@2023")
      cy.get('.w-48').click()
      cy.get('#swal2-title').should('contain.text','OOPS!')
    })
  })